src/objects/Constituency__c.object
<CustomObject>
    <description>EBoard constituencies (aka Logical Seats)</description>
    <fields>
        <fullName>ConstituencyName__c</fullName>
        <description>Name without the number of physical seats in it</description>
        <label>ConstituencyName</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Constituency__c</fullName>
        <formula>ConstituencyName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Constituency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executive_Committee_Seat__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executive Committee Seat</label>
        <referenceTo>EBoardSeats__c</referenceTo>
        <relationshipLabel>Constituencies</relationshipLabel>
        <relationshipName>Constituencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Constituency</label>
    <nameField>
        <label>SeatID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituencies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/EBoardSeats__c.object
<CustomObject>
    <description>All seats of the executive board, including appointee retirees and officers</description>
    <fields>
        <fullName>ConstituencyName__c</fullName>
        <formula>Constituency__r.ConstituencyName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ConstituencyName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Constituency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Constituency</label>
        <referenceTo>Constituency__c</referenceTo>
        <relationshipLabel>EBoardSeats</relationshipLabel>
        <relationshipName>EBoardSeats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Constituency_forAPI__c</fullName>
        <formula>Constituency__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Constituency_forAPI_Sandbox</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E_Board_Year__c</fullName>
        <label>E Board Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeatHolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual who is seated in this particular (sub seat) of the executive body.  Each individual can occupy one-and-only-one seat at any given time.  Persons who vie for a different position do not lose their current position, but will be unseated before being seated into any position they &quot;win&quot;.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EBoardSeats</relationshipLabel>
        <relationshipName>EBoardSeats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>EBoard or EComm</description>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>EBoardSeats</label>
    <nameField>
        <displayFormat>EBS{00000}</displayFormat>
        <label>EBoardSeatsID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBoardSeats</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>This will allow for multiple nested locations of a given employer.</description>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recruit__c.object
<CustomObject>
    <description>Political Campaigns/Shifts;</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Antelope Valley/Lancaster</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley/Lancaster</label>
                </value>
                <value>
                    <fullName>Antelope Valley(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(2-5)</label>
                </value>
                <value>
                    <fullName>Antelope Valley(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(5-8)</label>
                </value>
                <value>
                    <fullName>Arroyo Grande</fullName>
                </value>
                <value>
                    <fullName>Bakersfield</fullName>
                </value>
                <value>
                    <fullName>Bakersfield(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(2-5)</label>
                </value>
                <value>
                    <fullName>Bakersfield(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(5-8)</label>
                </value>
                <value>
                    <fullName>Baldwin</fullName>
                    <isActive>false</isActive>
                    <label>Baldwin</label>
                </value>
                <value>
                    <fullName>Chico</fullName>
                </value>
                <value>
                    <fullName>Fresno</fullName>
                </value>
                <value>
                    <fullName>Fresno Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Fresno Early(2-5)</label>
                </value>
                <value>
                    <fullName>Fresno GOTV AM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV PM</fullName>
                </value>
                <value>
                    <fullName>Fresno Late(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Fresno Late(5-8)</label>
                </value>
                <value>
                    <fullName>Lancaster</fullName>
                </value>
                <value>
                    <fullName>Lancaster Early(11-2)</fullName>
                    <isActive>false</isActive>
                    <label>Lancaster Early(11-2)</label>
                </value>
                <value>
                    <fullName>Lancaster Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Lancaster Early(2-5)</label>
                </value>
                <value>
                    <fullName>Lancaster GOTV AM</fullName>
                </value>
                <value>
                    <fullName>Lancaster GOTV PM</fullName>
                </value>
                <value>
                    <fullName>Lancaster Late(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Lancaster Late(2-5)</label>
                </value>
                <value>
                    <fullName>Lancaster Late(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Lancaster Late(5-8)</label>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Los Angeles Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles Early(2-5)</label>
                </value>
                <value>
                    <fullName>Los Angeles GOTV AM</fullName>
                </value>
                <value>
                    <fullName>Los Angeles GOTV PM</fullName>
                </value>
                <value>
                    <fullName>Los Angeles Late(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Los Angeles Late(5-8)</label>
                </value>
                <value>
                    <fullName>None</fullName>
                    <label>NONE</label>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Oakland Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Oakland Early(2-5)</label>
                </value>
                <value>
                    <fullName>Oakland GOTV AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recruit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the recruit is not a member or a community, leave this blank. Enter the recruit on the Family/Friends section.</inlineHelpText>
        <label>Recruit</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits</relationshipLabel>
        <relationshipName>Recruits3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Shift__c</fullName>
        <formula>IF( Attended__c =TRUE, CASE(  CreditShift__c , &apos;Full&apos;, 1, &apos;Half&apos;, 0.5,0), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shift Completed</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Volunteer Date</label>
        <type>Date</type>
    </fields>
    <label>Recruit</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recruit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recruits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/RecruitDataController.cls
public class RecruitDataController {

  class myClass {
    String Code;
    String Loc;
    String Ecom;
    Decimal Cnt;
  }

  @RemoteAction
  public static List <sObject> getData() {

    Integer i,l;
    Decimal cnt;
    String name,loc,ecom;
    List<ID> idArray = new List<Id>();
    Id idToAdd;
    List <sObject> returnData = new List <sObject>();

    for (list <EBoardSeats__c> dataList : [
      SELECT SeatHolder__c
      FROM EBoardSeats__c 
      WHERE E_Board_Year__c = '2017' AND Title__c = 'Executive Committee' And SeatHolder__c != null ORDER BY Constituency_forAPI__c ASC NULLS FIRST]) {
      l = dataList.size();
      for(i=0;i<l;i++) {
        idToAdd = dataList[i].SeatHolder__c;
        idArray.add(idToAdd);
      }
    }

    AggregateResult[] ecommCounts;
    AggregateResult[] regularCounts;

    ecommCounts = [
      SELECT  Recruit__r.Name EcommName, Recruit__r.Account.Constituency__r.Name , Location__c, Sum(Total_Shift__c) Cnt
      FROM Recruit__c 
      WHERE Recruit__c In :idArray AND Volunteer_Date__c >= 2018-05-01 
      GROUP BY Recruit__r.Name, Recruit__r.Account.Constituency__r.Name, Location__c];

    for(AggregateResult ecommCount : ecommCounts) {
        name = (String)  ecommCount.get('Name');
        loc  = (String)  ecommCount.get('Location__c');
        cnt  = (Decimal) ecommCount.get('Cnt');
        ecom = (String)  ecommCount.get('EcommName');
        System.debug('Name: ' + name);
        System.debug('Loc:  ' + loc);
        System.debug('Cnt:  ' + cnt);
        System.debug('Ecom: ' + ecom);
    }


      List <sObject> RegularShifts = [
      SELECT Recruit__r.Account.Constituency__r.Name , Location__c, Sum(Total_Shift__c)
      FROM Recruit__c 
      WHERE Recruit__c NOT In :idArray AND Volunteer_Date__c >= 2018-05-01 
      GROUP BY Recruit__r.Account.Constituency__r.Name, Location__c];

      System.debug(RegularShifts);  
  
    return RegularShifts;
  
  }

  @RemoteAction
  public static List <sObject> getTestData()  {

// Too deep (5 is limit)
// Recruit__r.Account.Constituency__r.Executive_Committee_Seat__r.SeatHolder__r.FirstName, 

    sObject[] testData = [
      SELECT Recruit__r.Id, Recruit__r.FirstName,Recruit__r.LastName,Volunteer_Date__c,Total_Shift__c ,
        Recruit__r.Account.Name,
        Recruit__r.Account.Constituency__r.ConstituencyName__c,
        Recruit__r.Account.Constituency__r.Executive_Committee_Seat__r.SeatHolder__c 
      FROM Recruit__c 
      WHERE Volunteer_Date__c >= 2018-01-01 AND Recruit__c != null AND Total_Shift__c > 0];

    return testData;

  }

  @RemoteAction
  public static List <myClass> getEcommData()  {
    Integer i,l;
    Decimal cnt;
    String code,loc,ecom;
    List<ID> idArray = new List<Id>();
    Id idToAdd;
    List <sObject> returnData = new List <sObject>();

    for (list <EBoardSeats__c> dataList : [
      SELECT SeatHolder__c,
        SeatHolder__r.FirstName,
        SeatHolder__r.LastName,
        ConstituencyName__c,
        Constituency_forAPI__c
      FROM EBoardSeats__c 
      WHERE E_Board_Year__c = '2017' AND Title__c = 'Executive Committee' And SeatHolder__c != null ORDER BY Constituency_forAPI__c ASC NULLS FIRST]) {
      l = dataList.size();
      for(i=0;i<l;i++) {
        myClass rec = new myClass();
        
        rec.Code = code;
        rec.Loc  = loc;
        rec.Ecom = ecom;
        rec.Cnt  = cnt;        
        
        idToAdd = dataList[i].SeatHolder__c;
        idArray.add(idToAdd);
      }
    }

    AggregateResult[] ecommCounts;
    AggregateResult[] regularCounts;

    ecommCounts = [
      SELECT  Recruit__r.Name EcName, Recruit__r.Account.Constituency__r.Name Code, Location__c, Sum(Total_Shift__c) Cnt
      FROM Recruit__c 
      WHERE Recruit__c In :idArray AND Volunteer_Date__c >= 2018-05-01 
      GROUP BY Recruit__r.Name, Recruit__r.Account.Constituency__r.Name, Location__c
    ];
                    
    List <myClass> myClassList = new List <myClass>();

    for(AggregateResult ecommCount : ecommCounts) {
        myClass rec = new myClass();

        code = (String)  ecommCount.get('Code');
        loc  = (String)  ecommCount.get('Location__c');
        cnt  = (Decimal) ecommCount.get('Cnt');
        ecom = (String)  ecommCount.get('EcName');
        System.debug('Name: ' + code);
        System.debug('Loc:  ' + loc);
        System.debug('Ecom: ' + ecom);
        System.debug('Cnt:  ' + cnt);        
        rec.Code = code;
        rec.Loc  = loc;
        rec.Ecom = ecom;
        rec.Cnt  = cnt;        
        myClassList.add(rec);
    }
    System.debug(myClassList);

    return myClassList;

  }

}